# -*- coding: utf-8 -*-
"""Proyecto Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMuO5XGGfnmE67SY1-ibgmpWTzZaD26-
"""

class Queue:
    def __init__(self):
        self.items = []
        self.head = 0

    def enqueue(self, x):
        self.items.append(x)

    def dequeue(self):
        if self.is_empty():
            return None
        item = self.items[self.head]
        self.head += 1
        return item

    def first(self):
        if self.is_empty():
            return None
        return self.items[self.head]


    def peek(self):
        return self.first()

    def is_empty(self):

        return self.head >= len(self.items)

    def size(self):
        return len(self.items) - self.head


class Graph:
    def __init__(self):
        self.adj = {}

    def add_edge(self, u, v, directed=False):
        """Añade una arista entre u y v."""
        if u not in self.adj: self.adj[u] = []
        if v not in self.adj: self.adj[v] = []

        self.adj[u].append(v)
        if not directed:
            self.adj[v].append(u)

    def bfs(self, start):
        """Regresa el orden de visita de los vértices."""
        if start not in self.adj: return []

        visited = set([start])
        order = []
        q = Queue()
        q.enqueue(start)

        while not q.is_empty():
            curr = q.dequeue()
            order.append(curr)

            for neighbor in self.adj.get(curr, []):
                if neighbor not in visited:
                    visited.add(neighbor)
                    q.enqueue(neighbor)

        return order

    def bfs_parents(self, start):
        """Regresa un diccionario parent[v] para reconstrucción de caminos."""
        if start not in self.adj: return {}

        visited = set([start])
        parent = {start: None}
        q = Queue()
        q.enqueue(start)

        while not q.is_empty():
            curr = q.dequeue()

            for neighbor in self.adj.get(curr, []):
                if neighbor not in visited:
                    visited.add(neighbor)
                    parent[neighbor] = curr
                    q.enqueue(neighbor)

        return parent

    def path_unweighted(self, start, goal):
        """Regresa la ruta (lista de vértices) si existe, o None si no."""

        if start not in self.adj or goal not in self.adj:
            return None

        parents = self.bfs_parents(start)


        if goal not in parents:
            return None


        path = []
        curr = goal
        while curr is not None:
            path.append(curr)
            curr = parents[curr]


        path.reverse()
        return path

def run_tests():
    print("--- PRUEBA 1: BFS en un grafo conexo ---")
    g1 = Graph()

    g1.add_edge('A', 'B')
    g1.add_edge('A', 'C')
    g1.add_edge('B', 'D')
    g1.add_edge('C', 'D')

    print("Grafo 1 (Conexo): A-B, A-C, B-D, C-D")
    orden_g1 = g1.bfs('A')
    print(f"Orden de visita desde 'A': {orden_g1}\n")


    print("--- PRUEBA 2: Grafo con  2 componentes ---")
    g2 = Graph()

    g2.add_edge(1, 2)
    g2.add_edge(2, 3)

    g2.add_edge(4, 5)

    print("Grafo 2 (Desconectado): Comp1(1-2-3), Comp2(4-5)")
    orden_g2 = g2.bfs(1)
    print(f"Orden de visita desde '1' (Solo visita la componente 1): {orden_g2}\n")


    print("--- PRUEBA 3: Rutas no ponderadas ---")




    start_node = 1
    goal_node_exists = 3
    path_exists = g2.path_unweighted(start_node, goal_node_exists)
    print(f"Camino de {start_node} a {goal_node_exists}: {path_exists}")


    goal_node_missing = 5
    path_missing = g2.path_unweighted(start_node, goal_node_missing)
    print(f"Camino de {start_node} a {goal_node_missing}: {path_missing}")


if __name__ == "__main__":
    run_tests()